version: '3'

volumes:
  postgres_volume:

services:
  pg:
    image: postgres:16
    container_name: postgres
    environment:
      - POSTGRES_DB=${PG_NAME}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
  auth:
    depends_on:
      - pg
    image: auth
    container_name: auth
    build: .
    ports:
      - "${HTTP_PORT}:8080"
      - "${GRPC_PORT}:50051"
    volumes:
      - ./.env:/root/.env 
      - ./.auth.env:/root/.auth.env
    expose:
      - "${HTTP_PORT}"
      - "${GRPC_PORT}"